[package]
name = "LLM_in_Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
# This is how I load the actual vocabulary used to train the BPE encoder
bpe-tokenizer = { version = "0.1.4", features = ["default-medium"]}
tch = "0.20.0"
tiktoken-rs = "0.7.0"
